### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS  secure channel

### ISSUE THREAD

**Issue by kf6ntg** [CityofSantaMonica/SODA.NET#51]
Hello,

On my desktop PC running windows 7 SODA.net works fine. However on my Windows Server 2008 R2 box I received this error: 

"The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

Here is an MSDN article with help:

http://blogs.msdn.com/b/deva/archive/2009/05/23/ews-throws-the-underlying-connection-was-closed-could-not-establish-trust-relationship-for-the-ssl-tls-secure-channel.aspx 

Have you ran into this problem before? Do you know if the solution listed in the MSDN article can be added to SODA.net?

BTW I'm using SODA.net for work at the County of Sonoma, my name is Brian and I work in the ISD department.

**Comment by thekaveman** [comment]
@kf6ntg so this is in the context of using one of the `EwsClient` helper classes in `SODA.Utilities`?

Can you verify which version of EWS you are trying to connect to? We've only provided implementations for 2007 SP1 and 2010 SP2, there could be a version mismatch.

We (City of Santa Monica) have many processes running on a 2008 R2 server, connecting to EWS 2010 SP2 (we used to be on 2007 SP1) - but I've never seen this issue come up.

**Comment by kf6ntg** [comment]
Sorry I'm not entirely sure if my code is using the EwsClient helper classes. I can reproduce the error with just the code snippet below.

I am pushing a CSV file up to Socrata Open Data.


var client = new SodaClient(HostURI, AppToken, UserName, Password);
string csvData = File.ReadAllText(FilePathToUploadFile);
SodaResult soddaResultObject = client.Upsert(csvData, SodaDataFormat.CSV, DataSetResourceID);

Does this help?

Problem doesn't show up on a windows 7 desktop on County domain.
Problem does show up on windows server 2008 r2 on County domain.

**Comment by thekaveman** [comment]
Ahhh, I just assumed since the MSDN article you linked was focused on EWS connection issues.

Is it possible that your Server 2008 R2 is blocking outgoing SSL connections? One way you might check is to try to browse to an HTTPS site from a browser running on the server itself.

@chrismetcalf does this error message / scenario sound familiar to you, from the receiving end?

**Comment by chrismetcalf** [comment]
99.9% of the time that I've seen it (mostly for other languages, this is the first time I've seen it for .NET), its because your root SSL CA certificates are out of date. How you update them depends on your OS and your development environment.

The fact that it occurs on Server 2008 but not on Windows 7 would seem to confirm that. The 2008 box probably has out of date root certificates, and the domain you're accessing is secured with a CA that has been established more recently. Its very likely that if you went to that domain in Internet Explorer, it'd also complain about the SSL certificate.

The best route is probably to first upgrade the 2008 machine with the latest service packs and security updates.

If that doesn't work, here's an MSDN article on manually installing a new root certificate: https://msdn.microsoft.com/en-us/library/cc750534.aspx

**Comment by kf6ntg** [comment]
Thanks guys updating the root SSL CA did the trick! Everything is working now.

**Comment by thekaveman** [comment]
Awesome! Thanks @chrismetcalf for that info.

I will close this issue now.
