### ISSUE TITLE
Upload/download files - Blob datatype columns

### ISSUE THREAD

**Issue by simplecoder** [CityofSantaMonica/SODA.NET#55]
Is it possible to upload files to, or download files from, Blob datatype columns in Socrata?

**Comment by thekaveman** [comment]
Thank you for the question. This is not supported, as Socrata does not [document that column type](https://dev.socrata.com/docs/datatypes).

But can you point me to a public dataset with such a column, so I can investigate further?

**Comment by simplecoder** [comment]
Ok good to know, I did look at your source code and it didn't seem possible but wanted to double check.
Here is an example dataset - https://data.kingcounty.gov/Records/Superior-Court-Records-from-microfiche/vu5j-8bgd

**Comment by allejo** [comment]
Seems like the links to files provided in that dataset point to `http://www.kingcounty.gov/` or  `http://your.kingcounty.gov/` which means that King County is hosting the files themselves (since Socrata is located at `https://data.kingcounty.gov/`). Then in the dataset, they are just providing the URLs as [plain text](https://socrata.github.io/datasync/resources/conditions-restrictions.html)&mdash;which supports formatting URLs&mdash;and file sizes as [numbers](https://dev.socrata.com/docs/datatypes/number.html#,).

**Comment by simplecoder** [comment]
Thanks @allejo

**Comment by thekaveman** [comment]
Yeah I think you're right @allejo 

It looks like those columns are using an older type `WebsiteUrl`, and in that case, we do have a [model](/CityofSantaMonica/SODA.NET/blob/master/SODA/Models/WebsiteUrlColumn.cs) that supports deserializing that column type.

Please re-open if this doesn't answer your question. (Or feel free to open new issues if you have further questions).
