### ISSUE TITLE
Ensure that SODA.NET uses TLS 1.1 or greater

### ISSUE THREAD

**Issue by chrismetcalf** [CityofSantaMonica/SODA.NET#65]
As part of our efforts to continually improve security around the Socrata platform, we are deprecating the TLS 1.0 protocol for clients connecting to the Socrata platform and APIs:

https://support.socrata.com/hc/en-us/articles/235267087

Can we make sure that SODA.NET disables TLS 1.0 as a connection protocol and selects TLS 1.1 or higher?

**Comment by chrismetcalf** [comment]
I think this may be the option that you want to set: http://stackoverflow.com/a/26392698/1000222

**Comment by dtsao** [comment]
Calling:
`
System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;
`
before calling any SODA.NET methods worked in my application. Thanks

**Comment by thekaveman** [comment]
Thanks for submitting the issue @chrismetcalf, and for your confirmation @dtsao.

We'd be happy to accept a PR if someone wanted to implement this in the library. I think [`SodaRequest`](https://github.com/CityofSantaMonica/SODA.NET/blob/master/SODA/SodaRequest.cs#L36) is probably the place to enforce this for now.

In the future we can look at upgrading support to .NET 4.6, since it has better support for TLS.

**Comment by thekaveman** [comment]
Yeah so, we just got bit by this issue in our own processes.... :man_facepalming: 

I'll try to get a fix in the library deployed this week.
